Parsing null fields with `jq`
When AWS returns a the associated metadata, it will fail to parse with
`jq` when a field contains a `null` value.

```Traceback (most recent call last):
  File "snucovery/__init__.py", line 44, in <module>
    main()
  File "snucovery/__init__.py", line 33, in main
    filtered_items = pyjq.all(jq_filter, items[service][service_attr])
  File "/Users/john.martin/.socrata/snucovery/.venv/lib/python3.7/site-packages/pyjq.py", line 49, in all
    return compile(script, vars, library_paths).all(_get_value(value, url, opener))
  File "_pyjq.pyx", line 209, in _pyjq.Script.all (_pyjq.c:2561)
_pyjq.ScriptRuntimeError: Cannot iterate over null (null)```

Luckily, `jq` has the ability to to do some validation against the
dataset so that we can handle the null fields with `jq`.